server:
  port: 8080
---
spring:
  profiles:
    - dev
    - default
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5433/shipit'
    username: 'postgres'
    password: 'postgres'
  flyway:
    enabled: true
    outOfOrder: true
    validateOnMigrate: true
    locations: ['classpath:db/migrations']
---
spring:
  profiles:
    - prod
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://35.246.209.154:5432/postgres'
    username: 'postgres'
    password: 'servicypw'
  flyway:
    enabled: true
    outOfOrder: true
    validateOnMigrate: true
    locations: ['classpath:db/migrations']